services:
  svmenu:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: svmenu
    working_dir: /app
    volumes:
      - ../:/app
    entrypoint: ["poetry", "run", "sv-menu"]
